  CREATE TABLE "CICD"."TREES"
   (	"TREE_ID" NUMBER(6,0),
	"TREE_NAME" VARCHAR2(200) COLLATE "USING_NLS_COMP",
	"TREE_STREET" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"TREE_CITY" VARCHAR2(200) COLLATE "USING_NLS_COMP",
	"TREE_STATE" VARCHAR2(200) COLLATE "USING_NLS_COMP",
	"TREE_ZIP" NUMBER,
	"TREE_DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"SUBMITTER_NAME" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"SUBMITTER_EMAIL" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"SUBMITTION_DATE" TIMESTAMP(6),
	"TREE_PICTURE" BLOB
   ) DEFAULT COLLATION "USING_NLS_COMP";
